name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - sec_deploy

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Angular
<<<<<<< HEAD
        run: |
          npm run build -- --configuration production --base-href=/mechanicapp/
=======
        run: ng build --configuration production --base-href=/mechanicapp/ 
>>>>>>> 63b4aec039d0fcadbdec2b09ca7a8faa865d8386

<<<<<<< HEAD
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
=======
      - name: Deploy
        uses: angular-cli-ghpages
>>>>>>> 63b4aec039d0fcadbdec2b09ca7a8faa865d8386
        with:
          path: sec_deploy/mechanicapp

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
